---
- name: Delete ServiceAccount
  k8s_v1_service_account:
    name: "{{ APPLICATION_NAME }}"
    namespace: "{{ namespace }}"
    state: absent

- name: Delete RoleBinding
  k8s_v1beta1_role_binding:
    name: "{{ APPLICATION_NAME }}-view"
    namespace: "{{ namespace }}"
    state: absent

- name: Delete API service
  k8s_v1_service:
    name: "{{ APPLICATION_NAME }}"
    namespace: "{{ namespace }}"
    state: absent

- name: Delete Cluster service
  k8s_v1_service:
    name: "{{ APPLICATION_NAME }}-cluster"
    namespace: "{{ namespace }}"
    state: absent

- name: Delete ConfigMap
  k8s_v1_config_map:
    name: "{{ APPLICATION_NAME }}"
    namespace: "{{ namespace}}"
    state: absent

- name: Delete StatefulSet
  k8s_v1beta1_stateful_set:
    name: "{{ APPLICATION_NAME }}"
    namespace: "{{ namespace}}"
    state: absent

- name: Delete ImageStream
  openshift_v1_image_stream:
    name: "{{ APPLICATION_NAME }}"
    namespace: "{{ namespace}}"
    state: absent
