---
- name: Delete ServiceAccount
  k8s:
    kind: ServiceAccount
    api_version: v1
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    state: absent

- name: Delete RoleBinding
  k8s:
    kind: RoleBinding
    api_version: rbac.authorization.k8s.io/v1
    name: "{{ application_name }}-view"
    namespace: "{{ namespace }}"
    state: absent

- name: Delete API service
  k8s:
    kind: Service
    api_version: v1
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    state: absent

- name: Delete Cluster service
  k8s:
    kind: Service
    api_version: v1
    name: "{{ application_name }}-cluster"
    namespace: "{{ namespace }}"
    state: absent

- name: Delete ConfigMap
  k8s:
    kind: ConfigMap
    api_version: v1
    name: "{{ application_name }}"
    namespace: "{{ namespace}}"
    state: absent

- name: Delete StatefulSet
  k8s:
    kind: StatefulSet
    api_version: apps/v1
    name: "{{ application_name }}"
    namespace: "{{ namespace}}"
    state: absent

- name: Delete StatefulSet's PVCs
  k8s:
    kind: PersistentVolumeClaim
    api_version: v1
    name: "elasticsearch-persistent-{{ application_name }}-{{ item }}"
    namespace: "{{ namespace}}"
    state: absent
  with_sequence: start=0 end="{{ cluster_size - 1}}"

- name: Delete ImageStream
  k8s:
    kind: ImageStream
    api_version: image.openshift.io/v1
    name: "{{ application_name }}"
    namespace: "{{ namespace}}"
    state: absent
