---

- name: Create ImageStream
  k8s:
    state: present
    definition: '{{ lookup("template", "elasticsearch-is.yml.j2") | from_yaml }}'

- name: Create ServiceAccount
  k8s:
    state: present
    kind: ServiceAccount
    api_version: v1
    namespace: '{{ namespace }}'
    name: '{{ application_name }}'

- name: Create RoleBinding
  k8s:
    state: present
    definition:
      kind: RoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: "{{ application_name }}-view"
        namespace: "{{ namespace }}"
      roleRef:
        name: view
        kind: ClusterRole
      subjects:
      - kind: ServiceAccount
        name: "{{ application_name }}"
        namespace: "{{ namespace }}"

- name: Create API service
  k8s:
    state: present
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: "{{ application_name }}"
        namespace: "{{ namespace }}"
      spec:
        selector:
          app: "{{ application_name }}"
        ports:
          - name: restapi
            port: 9200
            targetPort: 9200

- name: Create Cluster service
  k8s:
    state: present
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: "{{ application_name }}"
        namespace: "{{ namespace }}"
      spec:
        selector:
          app: "{{ application_name }}"
        ports:
          - name: cluster
            port: 9300
            target_port: 9300

- name: Process StatefulSet from template
  template:
    src: elasticsearch-statefulset.yml.j2
    dest: "/tmp/elasticsearch/elasticsearch-statefulset.yml"
  register: statefulset

- name: Create StatefulSet
  k8s:
    state: present
    definition: '{{ lookup("template", "elasticsearch-statefulset.yml.j2") | from_yaml }}'

##############################################################################
## Bindable services must make credentials available to the Ansible Service
## Broker during the provision stage.  They will later be made available to
## applications after a binding is created.
## https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/design.md#using-a-service-instance
##############################################################################
- name: encode bind credentials
  asb_encode_binding:
    fields:
      ELASTICSEARCH_URL: 'http://{{ application_name }}:9200'
