---
- name: "[SET UP] tmp folder"
  file:
    path: /tmp/elasticsearch
    state: directory

- name: Process ImageStream from template
  template:
    src: elasticsearch-is.yml.j2
    dest: "/tmp/elasticsearch/elasticsearch-is.yml"
  register: is

- name: Create ImageStream
  openshift_v1_image_stream:
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    state: present
    src: "{{ is.dest | default(is.path) }}"

- name: Create ServiceAccount
  k8s_v1_service_account:
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    state: present

- name: Create RoleBinding
  k8s_v1beta1_role_binding:
    name: "{{ application_name }}-view"
    namespace: "{{ namespace }}"
    state: present
    role_ref_name: view
    role_ref_kind: ClusterRole
    subjects:
    - kind: ServiceAccount
      name: "{{ application_name }}"
      namespace: "{{ namespace }}"

- name: Create API service
  k8s_v1_service:
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    state: present
    selector:
      app: "{{ application_name }}"
    ports:
      - name: restapi
        port: 9200
        target_port: 9200

- name: Create Cluster service
  k8s_v1_service:
    name: "{{ application_name }}-cluster"
    namespace: "{{ namespace }}"
    state: present
    selector:
      app: "{{ application_name }}"
    ports:
      - name: cluster
        port: 9300
        target_port: 9300

- name: Process StatefulSet from template
  template:
    src: elasticsearch-statefulset.yml.j2
    dest: "/tmp/elasticsearch/elasticsearch-statefulset.yml"
  register: statefulset

- name: Create StatefulSet
  k8s_v1beta1_stateful_set:
    name: "{{ application_name }}"
    namespace: "{{ namespace}}"
    state: present
    src: "{{ statefulset.dest | default(statefulset.path) }}"

##############################################################################
## Bindable services must make credentials available to the Ansible Service
## Broker during the provision stage.  They will later be made available to
## applications after a binding is created.
## https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/design.md#using-a-service-instance
##############################################################################
- name: encode bind credentials
  asb_encode_binding:
    fields:
      ELASTICSEARCH_URL: 'http://{{ application_name }}:9200'
