---
- name: "[TESTS][{{ plan_id | upper }}] Load default variables for testing"
  include_vars: '{{ item }}'
  with_items:
    - test_defaults.yml
    - test_{{ plan_id }}_defaults.yml

- name: "[TESTS][{{ plan_id | upper }}] Create project for namespace"
  k8s:
    state: present
    kind: Project
    api_version: project.openshift.io/v1
    name: '{{ namespace }}'

- name: "[TESTS][{{ plan_id | upper }}] Run the provision role."
  import_role:
    name: es-apb
    tasks_from: provision
    defaults_from: provision

- name: "[TESTS][{{ plan_id | upper }}] Run the test role."
  import_role:
    name: es-apb
    tasks_from: test-provision

- name: "[TESTS][{{ plan_id | upper }}] Run the deprovision role."
  import_role:
    name: es-apb
    tasks_from: deprovision

- name: "[TESTS][{{ plan_id | upper }}] Run the deprovision test role."
  import_role:
    name: es-apb
    tasks_from: test-deprovision

- name: "[TESTS][{{ plan_id | upper }}] Remove binding secret."
  k8s:
    state: absent
    kind: Secret
    api_version: v1
    name: "{{ lookup('env', 'POD_NAME') }}"
    namespace: '{{ namespace }}'
