---
- name: Test es-apb
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
  - vars/common.yml
  roles:
  - role: ansibleplaybookbundle.asb-modules
  tasks:
  - name: "[TESTS] Start tests"
    include_tasks: test_plan.yml
    with_items:
      - persistent
      - ephemeral
      - ha
    loop_control:
      loop_var: plan_id
  - name: "[TEST][ALL] Success"
    asb_save_test_result:
      msg: 'All tests passed!'
    when: travis is undefined
